version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: soru86
      POSTGRES_PASSWORD: C@lmD0wn@123
      POSTGRES_DB: super_shop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --http-relative-path=/auth
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data

  backend-gateway:
    build:
      context: .
      dockerfile: apps/backend-gateway/Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://soru86:C@lmD0wn@123@postgres:5432/super_shop?schema=public
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/auth/realms/super-shop
      KEYCLOAK_CLIENT_ID: super-shop-console
      KEYCLOAK_CLIENT_SECRET: local-secret
      PORT: 4000
    depends_on:
      - postgres
      - keycloak
    ports:
      - "4000:4000"

  frontend-shell:
    build:
      context: .
      dockerfile: apps/frontend-shell/Dockerfile
    environment:
      NODE_ENV: development
      VITE_GRAPHQL_HTTP: http://localhost:4000/graphql
      VITE_KEYCLOAK_URL: http://localhost:8080/auth
    ports:
      - "4173:4173"
    depends_on:
      - backend-gateway

  mfe-customer:
    build:
      context: .
      dockerfile: apps/mfe-customer/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "4174:4174"
    depends_on:
      - backend-gateway

  mfe-admin:
    build:
      context: .
      dockerfile: apps/mfe-admin/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "4175:4175"
    depends_on:
      - backend-gateway

networks:
  default:
    name: super-shop-net
