apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-gateway
  namespaceSelector:
    matchNames:
      - super-shop
  endpoints:
    - port: http
      path: /metrics
      interval: 30s


