package com.example.inventory.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAllPropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertProductStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertProductStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAllUpdatablePropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertProductStatusUpdatableFieldsEquals(expected, actual);
        assertProductStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusAutoGeneratedPropertiesEquals(ProductStatus expected, ProductStatus actual) {
        assertThat(expected)
            .as("Verify ProductStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusUpdatableFieldsEquals(ProductStatus expected, ProductStatus actual) {
        assertThat(expected)
            .as("Verify ProductStatus relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getIsDefault()).as("check isDefault").isEqualTo(actual.getIsDefault()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductStatusUpdatableRelationshipsEquals(ProductStatus expected, ProductStatus actual) {
        // No relationships to verify for ProductStatus
    }
}
